In [29]:
import pandas as pd
from Bio import SeqIO

In [2]:
filepath = "/home/chen1i6c04/下載/sequence.gb"

In [3]:
records = SeqIO.parse(filepath, 'genbank')

In [4]:
record = next(records)

In [95]:
chrom = 'HF937208.1'
positions = []
for feature in record.features:
    convertor = {1: '+', -1: '-'}
    if feature.type == "rRNA":
        locus_tag = dict(feature.qualifiers)['locus_tag'][0]
        strand = feature.strand
        start, end = feature.location.start.position, feature.location.end.position
        positions.append((chrom, start, end, locus_tag, convertor[strand]))

In [96]:
df = pd.DataFrame(positions)

In [98]:
df.to_csv('sequences.bed', sep='\t', index=False, header=False)

In [97]:
df

             0        1        2             3  4
0   HF937208.1   289177   290721  DT104_r00001  +
1   HF937208.1   291242   294335  DT104_r00002  +
2   HF937208.1   294518   294640  DT104_r00003  +
3   HF937208.1  2865373  2865495  DT104_r00004  -
4   HF937208.1  2865687  2867415  DT104_r00005  -
5   HF937208.1  2867427  2868687  DT104_r00006  -
6   HF937208.1  2869049  2870593  DT104_r00007  -
7   HF937208.1  3599891  3600004  DT104_r00008  -
8   HF937208.1  3600129  3600249  DT104_r00009  -
9   HF937208.1  3600443  3603437  DT104_r00010  -
10  HF937208.1  3603790  3605334  DT104_r00011  -
11  HF937208.1  4176449  4177991  DT104_r00012  +
12  HF937208.1  4178335  4181327  DT104_r00013  +
13  HF937208.1  4181417  4181539  DT104_r00014  +
14  HF937208.1  4272374  4273916  DT104_r00015  +
15  HF937208.1  4274419  4277411  DT104_r00016  +
16  HF937208.1  4277500  4277622  DT104_r00017  +
17  HF937208.1  4428039  4429583  DT104_r00018  +
18  HF937208.1  4430094  4433086  DT104_r00019  +
19  HF937208.1  4433278  4433398  DT104_r00020  +
20  HF937208.1  4471580  4473122  DT104_r00021  +
21  HF937208.1  4473515  4476509  DT104_r00022  +
22  HF937208.1  4476701  4476823  DT104_r00023  +

In [71]:
start, end = end, start

In [72]:
start, end

(4476823, 4476701)