In [25]:
from collections import defaultdict
import pandas as pd
from Bio import SeqIO

In [26]:
template_file = '/media/NGS/Nanopore_1/mNGS/20210121_spike/untrim/unicycler/assembly.fasta'

In [29]:
template_size = sum(len(record.seq) for record in SeqIO.parse(template_file, 'fasta'))

In [39]:
names = ["Query","Q_length","Q_start","Q_end","Strand","Template","T_length","T_start",
         "T_end","N_res_matches","Align_block",]

In [72]:
df = pd.read_csv('/media/NGS/Nanopore_1/mNGS/20210121_spike/untrim/overlap/barcode12.paf', sep='\t', names=names, usecols=range(0, 11))

In [73]:
cover_range = defaultdict(set)

In [74]:
for template, start, end in zip(df['Template'], df['T_start'], df['T_end']):
    cover_range[template].update(list(range(start, end+1)))

In [75]:
cover_size = sum(len(value) for value in cover_range.values())

In [76]:
round(cover_size/template_size*100, 2)

94.24

In [83]:
df

,Query,Q_length,Q_start,Q_end,Strand,Template,T_length,T_start,T_end,N_res_matches,Align_block
0,contig_1,248737,32,248708,-,1,5429210,2281990,2530773,240950,249185
1,contig_10,220188,19,216397,+,1,5429210,5074365,5290793,209729,216684
2,contig_10,220188,216459,220109,-,1,5429210,5286015,5290744,378,4733
3,contig_11,183284,0,183280,-,1,5429210,446167,629371,169604,183860
4,contig_12,99961,8,99960,+,1,5429210,344554,444491,94377,100226
5,contig_13,142332,4,142267,+,1,5429210,4932648,5075069,133638,142765
6,contig_14,178837,24,178815,+,1,5429210,1165408,1344053,167730,179342
7,contig_15,168970,8,168914,+,1,5429210,1406303,1575240,158079,169442
8,contig_16_polish,173134,38,127661,-,2,193802,0,127335,123152,127801
9,contig_16_polish,173134,127662,173124,-,2,193802,148339,193801,45254,45463
10,contig_17_polish,60369,0,52922,+,4,60310,7384,60305,51759,52946
11,contig_17_polish,60369,52935,60368,+,4,60310,8,7380,6515,7437
12,contig_18,161793,0,161745,-,1,5429210,629469,791218,145348,162531
13,contig_19,76552,2,76509,-,1,5429210,5294815,5371309,66986,76883
14,contig_2,73041,0,73034,+,1,5429210,1082845,1155942,69862,73219
15,contig_20,60336,11490,60335,+,1,5429210,7082,56011,45230,49054
16,contig_20,60336,11,11490,+,1,5429210,5400676,5412148,9876,11535
17,contig_21,108104,7,107712,+,1,5429210,4383328,4491071,100794,108048
18,contig_22_polish,39243,0,30293,+,5,39248,8946,39239,29248,30293
19,contig_22_polish,39243,30305,39243,+,5,39248,3,8941,8938,8938
20,contig_23,136717,0,136696,-,1,5429210,2073304,2210084,129253,137118
21,contig_24,42611,52,42603,+,1,5429210,299779,342404,36778,42888
22,contig_25,26540,2,26520,+,1,5429210,5372684,5399175,24452,26600
23,contig_26,144113,28,144112,-,1,5429210,861105,1005222,137305,144485
24,contig_27,76222,6,76213,+,1,5429210,1006823,1083154,71892,76465
25,contig_28_polish,10040,1349,10031,-,6,10060,1373,10055,8682,8682
26,contig_28_polish,10040,0,1340,-,6,10060,4,1344,1340,1340
27,contig_29_polish,10938,3576,9158,+,7,5596,7,5589,5582,5582
28,contig_29_polish,10938,6,3562,+,7,5596,2033,5589,3534,3556
29,contig_29_polish,10938,9172,10932,+,7,5596,7,1763,1659,1764
30,contig_3,440942,4,440939,+,1,5429210,2531356,2972441,429885,441661
31,contig_30,139942,12071,139934,+,1,5429210,172569,300604,121787,128310
32,contig_30,139942,26,11526,-,1,5429210,173324,185135,7555,11896
33,contig_31,430336,4,430336,+,1,5429210,4496289,4926905,410817,431538
34,contig_32_polish,65478,14269,65478,-,3,65499,14287,65496,51184,51209
35,contig_32_polish,65478,0,14260,-,3,65499,6,14266,14248,14260
36,contig_33,107808,3,107807,+,1,5429210,56797,164720,100271,108174
37,contig_34,52644,0,52628,+,1,5429210,2225793,2278434,48596,52806
38,contig_4,373184,6,373178,-,1,5429210,3407333,3780580,361190,373760
39,contig_5,367494,2,367490,+,1,5429210,2982305,3349873,355332,368106
40,contig_6,24438,0,24414,+,1,5429210,3367601,3392039,23990,24457
41,contig_7,575493,4,575489,+,1,5429210,3806642,4382355,560041,576479
42,contig_8,20034,0,20034,+,1,5429210,3785870,3805907,19086,20080
43,contig_9,453119,11,453062,-,1,5429210,1577956,2031029,434638,453890